# Generated by Django 5.2 on 2025-10-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('skill', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, help_text='YouTube or video link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
