# Generated by Django 5.2 on 2025-10-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_golpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Golpo',
        ),
    ]
