# Generated by Django 5.2.6 on 2026-09-13

from decimal import Decimal

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_golpo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order_number',
                    models.CharField(
                        default=store.models.generate_order_number,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=255)),
                (
                    'address_line_2',
                    models.CharField(blank=True, default='', max_length=255),
                ),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                (
                    'subtotal',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=12,
                    ),
                ),
                (
                    'total',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=12,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('confirmed', 'Confirmed'),
                            ('processing', 'Processing'),
                            ('shipped', 'Shipped'),
                            ('delivered', 'Delivered'),
                            ('cancelled', 'Cancelled'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='orders',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('subtotal__gte', 0)),
                        name='order_subtotal_nonnegative',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('total__gte', 0)),
                        name='order_total_nonnegative',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('product_name', models.CharField(max_length=255)),
                (
                    'unit_price',
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ('quantity', models.PositiveIntegerField()),
                (
                    'line_total',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='store.order',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='order_items',
                        to='store.product',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('unit_price__gte', 0)),
                        name='order_item_unit_price_nonnegative',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('quantity__gt', 0)),
                        name='order_item_quantity_positive',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('line_total__gte', 0)),
                        name='order_item_line_total_nonnegative',
                    ),
                ],
            },
        ),
    ]
